analytics: {}
color:
  brandColors:
    - '#f3f3f3'
    - '#181818'
    - '#51504e'
    - '#958b82'
    - '#c6ab80'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.616139
  saturation: 0.689365
cta: {}
layout_spectrum: 0.25188
name: 'Athenart Jewelry '
opengraph: {}
purpose: []
typography_spectrum: 0.49872
