name: 'Athenart Jewelry '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#dcd7d3'
    - '#786451'
    - '#907d63'
    - '#beb695'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
