name: 'Athenart Jewelry '
favicon: null
layout_spectrum: 0.817372701363638
typography_spectrum: 0.31985738780349493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#181818'
    - '#51504e'
    - '#958b82'
    - '#c6ab80'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6161391658242792
purpose: []
